### ISSUE TITLE
I can't find the file: "Statues_4.pcd"

### ISSUE THREAD

**Issue by SmartKangJohn** [PointCloudLibrary/data#10]

**Comment by mvieth** [comment]
How did you become aware of the file/why do you think it has to exist? Is it mentioned in a tutorial or somewhere else?

**Comment by mvieth** [comment]
Oh, I see: it is mentioned in the conditional euclidean clustering tutorial. The file can be downloaded here: https://sourceforge.net/projects/pointclouds/files/PCD%20datasets/Trimble/Outdoor1/
